apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx-forward-proxy.fullname" . }}
  labels:
{{ include "nginx-forward-proxy.labels" . | indent 4 }}
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
{{ include "nginx-forward-proxy.selectorLabels" . | indent 4 }}
