apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nginx-forward-proxy.fullname" . }}
  labels:
{{ include "nginx-forward-proxy.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: {{ .Values.strategy.type }}
    rollingUpdate:
      maxUnavailable: {{ .Values.strategy.rollingUpdate.maxUnavailable }}
      maxSurge: {{ .Values.strategy.rollingUpdate.maxSurge }}
  selector:
    matchLabels:
{{ include "nginx-forward-proxy.selectorLabels" . | indent 6 }}
  template:
    metadata:
      labels:
{{ include "nginx-forward-proxy.selectorLabels" . | indent 8 }}
      annotations:
        ad.datadoghq.com/nginx.logs: '[{"source":"nginx","service":"nginx"}]'
        ad.datadoghq.com/nginx.checks: |
          {
            "nginx": {
              "init_config": {},
              "instances": [
                {
                  "nginx_status_url":"http://%%host%%:81/nginx_status/"
                }
              ]
            }
          }  
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
            - containerPort: 81
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              port: {{ .Values.readinessProbe.port }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: {{ .Values.livenessProbe.port }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}